'use strict';
const TOTAL=30;
const screens=[...document.querySelectorAll('.screen')],tabs=[...document.querySelectorAll('.tab')];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='challenge'&&!quiz.length)startQuiz()}
tabs.forEach(t=>t.addEventListener('click',()=>showScreen(t.dataset.screen)));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.next)));
document.querySelectorAll('[data-practice]').forEach(b=>b.addEventListener('click',()=>{b.nextElementSibling.innerHTML='Answer: '+rich(b.dataset.practice)}));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,choice=a=>a[rnd(0,a.length-1)];
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)||1}function simp(n,d){const g=gcd(n,d);return[n/g,d/g]}function eq(a,b){return a[0]*b[1]===b[0]*a[1]}
function frac(n,d){return `<span class="frac"><span>${n}</span><i></i><span>${d}</span></span>`}function mixed(w,n,d){return `<span class="mixed"><strong>${w}</strong>${frac(n,d)}</span>`}
function expr(parts){return '<div class="math-row">'+parts.map(x=>Array.isArray(x)?frac(x[0],x[1]):x).join('')+'</div>'}
function rich(text=''){return String(text).replace(/\b(\d+)\/(\d+)\b/g,(_,n,d)=>frac(n,d))}
function richOption(text=''){return '<span class="rich-option">'+rich(text)+'</span>'}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rnd(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function fingerprint(q){return [q.topic,q.prompt,q.html||expr(q.parts||[]),JSON.stringify(q.answer)].join('|').replace(/\s+/g,' ')}
function unique(factory,seen){for(let tries=0;tries<80;tries++){const q=factory(),key=fingerprint(q);if(!seen.has(key)){seen.add(key);return q}}throw new Error('Could not generate a unique Fractions question: '+factory.name)}
function same(op='+'){const d=choice([4,5,6,7,8,9,10,12]);let a=rnd(1,d-2),b=rnd(1,d-2);if(op==='-'&&b>=a)[a,b]=[Math.max(a,b),Math.min(a,b)];if(op==='-'&&a===b)a=Math.min(d-1,a+1);const ans=simp(op==='+'?a+b:a-b,d);return{topic:'Same Denominators',prompt:op==='+'?'Add and simplify.':'Subtract and simplify.',parts:[[a,d],op,[b,d]],answer:ans,type:'fraction',solution:'Because the denominators are the same, work with the numerators and keep the denominator. Then simplify the result.'}}
function equivalent(){const d=choice([3,4,5,6,8]),n=rnd(1,d-1),m=rnd(2,4);return{topic:'Equivalent Fractions',prompt:'Find the missing numerator.',parts:[[n,d],'=',['?',d*m]],answer:n*m,type:'single',solution:'Equivalent fractions name the same amount. Multiply the numerator and denominator by the same factor.'}}
function simplifyQ(){const d=choice([3,4,5,6,8]),n=rnd(1,d-1),m=rnd(2,5);return{topic:'Simplifying',prompt:'Write this fraction in simplest form.',parts:[[n*m,d*m]],answer:simp(n*m,d*m),type:'fraction',strict:true,solution:'Find a common factor of the numerator and denominator. Divide both by the same factor until no common factor greater than 1 remains.'}}
function compare(){const d=choice([4,5,6,8,10]),a=rnd(1,d-1),b=rnd(1,d-1);return{topic:'Compare Fractions',prompt:'Choose the correct symbol.',parts:[[a,d],'___',[b,d]],answer:a>b?'>':a<b?'<':'=',type:'choice',options:['<','=','>'],solution:'The denominators are equal, so the fraction with the greater numerator is greater. If the numerators match, the fractions are equal.'}}
function partitionQ(){const d=choice([4,5,6,8]),n=rnd(2,d-1),split=rnd(1,n-1);return{topic:'Partition Fractions',prompt:'Which expression partitions this fraction correctly?',html:expr([[n,d],'=','?']),answer:(split+'/'+d+' + '+(n-split)+'/'+d),type:'choice',options:shuffle([split+'/'+d+' + '+(n-split)+'/'+d,(split+1)+'/'+d+' + '+(n-split)+'/'+d,split+'/'+(d+1)+' + '+(n-split)+'/'+d,n+'/'+d+' + 1/'+d]),solution:'Partitioning breaks a fraction into smaller fractions with the same total. '+n+'/'+d+' = '+split+'/'+d+' + '+(n-split)+'/'+d+'.'}}
function areaAdd(){const d=choice([4,6,8]),a=rnd(1,Math.floor(d/2)),b=rnd(1,d-a-1),ans=simp(a+b,d),cells=Array.from({length:d},(_,i)=>'<span class="'+(i<a?'part-a':i<a+b?'part-b':'')+'"></span>').join('');return{topic:'Area Model',prompt:'The rectangle is one whole. The first shaded part shows one fraction and the second shaded part shows another. What fraction is shaded altogether? Give the answer in simplest form.',html:'<div class="area-quiz" aria-label="'+(a+b)+' of '+d+' equal parts shaded in two groups">'+cells+'</div><p class="visual-hint">'+a+'/'+d+' + '+b+'/'+d+'</p>',answer:ans,type:'fraction',strict:true,solution:'The whole has '+d+' equal parts. '+a+' parts plus '+b+' parts gives '+(a+b)+'/'+d+', which simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function stripSubtract(){const d=choice([6,8,10]),a=rnd(Math.ceil(d/2),d-1),b=rnd(1,a-1),ans=simp(a-b,d),cells=Array.from({length:d},(_,i)=>'<span class="'+(i<a-b?'remaining':i<a?'removed':'')+'"></span>').join('');return{topic:'Strip Model',prompt:'The strip shows '+a+'/'+d+' selected, with '+b+'/'+d+' of that amount removed. What remains? Give the answer in simplest form.',html:'<div class="strip-quiz" aria-label="'+(a-b)+' of '+d+' parts remain and '+b+' selected parts are removed">'+cells+'</div>',answer:ans,type:'fraction',strict:true,solution:'Because the parts are all '+d+'ths, subtract the numerators: '+a+'/'+d+' − '+b+'/'+d+' = '+(a-b)+'/'+d+'. Simplify to '+ans[0]+'/'+ans[1]+'.'}}
function compareRelated(){const base=choice([6,8,10,12]),ds=[2,3,4,5,6].filter(x=>x<base&&base%x===0),d1=choice(ds),d2=base,a=rnd(1,d1-1),b=rnd(1,d2-1),left=a*(base/d1),cmp=left>b?'>':left<b?'<':'=';return{topic:'Compare Related Fractions',prompt:'Choose the correct symbol. Use equivalent fractions or a number line.',parts:[[a,d1],'___',[b,d2]],answer:cmp,type:'choice',options:['<','=','>'],solution:'Rename '+a+'/'+d1+' as '+left+'/'+base+'. Compare '+left+'/'+base+' with '+b+'/'+base+'. The correct symbol is '+cmp+'.'}}
function compareMixed(){const d=choice([4,5,6,8]),w=choice([1,2,3]),a=rnd(1,d-1),b=rnd(1,d-1),cmp=a>b?'>':a<b?'<':'=';return{topic:'Compare Mixed Numbers',prompt:'Choose the correct symbol.',html:expr([mixed(w,a,d),'___',mixed(w,b,d)]),answer:cmp,type:'choice',options:['<','=','>'],solution:'The whole-number parts are both '+w+', so compare the fractional parts. '+a+'/'+d+' '+cmp+' '+b+'/'+d+'.'}}
function numberLineAdd(){const d=choice([4,6,8]),a=rnd(1,Math.floor(d/2)),b=rnd(1,d-a),ans=simp(a+b,d),ticks=Array.from({length:d+1},(_,i)=>'<span class="nl-tick '+(i===a?'start':'')+' '+(i===a+b?'target':'')+'" style="left:'+(i/d*100)+'%"><i></i><b>'+(i===0?'0':i===d?'1':i===a?'start':i===a+b?'?':'')+'</b>'+(i===a+b?'<em aria-hidden="true">▲</em>':'')+'</span>').join('');return{topic:'Number Line Strategy',prompt:'Start at '+a+'/'+d+' and move forward '+b+'/'+d+'. Where do you land? Give the answer in simplest form.',html:'<div class="number-line-wrap"><div class="number-line" aria-label="Number line addition in '+d+'ths"><div class="nl-axis"></div>'+ticks+'</div></div>',answer:ans,type:'fraction',strict:true,solution:'On a number line, addition means moving forward. '+a+'/'+d+' + '+b+'/'+d+' = '+(a+b)+'/'+d+', which simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function related(op='+'){const pair=choice([[2,4],[2,6],[3,6],[4,8],[5,10],[6,12]]),d1=pair[0],d2=pair[1];let a=rnd(1,d1-1),b=rnd(1,d2-1);if(op==='-'&&a/d1<=b/d2){a=d1-1;b=1}const n=op==='+'?a*d2+b*d1:a*d2-b*d1;return{topic:'Related Denominators',prompt:(op==='+'?'Add':'Subtract')+' and simplify.',parts:[[a,d1],op,[b,d2]],answer:simp(n,d1*d2),type:'fraction',strict:true,solution:'Rename the fractions using a common denominator. Then work with the numerators, keep the common denominator and simplify.'}}
function improper(){const d=choice([3,4,5,6]),w=rnd(1,3),r=rnd(1,d-1),s=simp(r,d),n=w*s[1]+s[0];return{topic:'Mixed Numbers',prompt:'Change this improper fraction to a mixed number.',parts:[[n,s[1]]],answer:[w,s[0],s[1]],type:'mixed',solution:'Divide the numerator by the denominator. The quotient is the whole number and the remainder becomes the new numerator.'}}
function toImproper(){const d=choice([3,4,5,6]),w=rnd(1,3),n=rnd(1,d-1),s=simp(n,d);return{topic:'Mixed Numbers',prompt:'Change this mixed number to an improper fraction.',html:expr([mixed(w,s[0],s[1])]),answer:[w*s[1]+s[0],s[1]],type:'fraction',solution:'Multiply the whole number by the denominator, add the numerator, and keep the same denominator.'}}
function triple(){const base=choice([6,8,10,12]),divs=[2,3,4,5,6].filter(x=>x<base&&base%x===0),d1=choice(divs),d2=base,d3=base;const a=rnd(1,d1-1),b=rnd(1,Math.max(1,base-3)),c=rnd(1,Math.min(2,base-1));let n=a*(base/d1)+b-c;if(n<=0)n=a*(base/d1)+b;return{topic:'Multi-step Fractions',prompt:'Calculate from left to right. Rename the fractions with a common denominator, then simplify your final answer.',parts:[[a,d1],'+',[b,d2],'−',[c,d3]],answer:simp(n,base),type:'fraction',strict:true,solution:'Rename every fraction with the common denominator shown by the related denominators. Calculate from left to right, then simplify.'}}
function wordProblem(){return{topic:'Problem Solving',prompt:'A recipe uses 1/2 cup of oats and 1/4 cup of nuts. How much is used altogether?',parts:[[1,2],'+',[1,4]],answer:[3,4],type:'fraction'}}
function visualBar(){const d=choice([6,8,10,12]),n=rnd(2,d-2),ans=simp(n,d),cells=Array.from({length:d},(_,i)=>'<span class="bar-cell '+(i<n?'filled':'')+'"></span>').join('');return{topic:'Visual Fractions',prompt:'The bar represents one whole. What fraction is shaded? Give your answer in simplest form.',html:'<div class="fraction-visual" aria-label="'+n+' of '+d+' equal parts shaded">'+cells+'</div>',answer:ans,type:'fraction',strict:true,solution:'Count the equal parts: '+n+' of '+d+' are shaded. This is '+n+'/'+d+'. Simplify to '+ans[0]+'/'+ans[1]+'.'}}
function numberLine(){const d=choice([4,5,6,8]),n=rnd(1,d-1),ans=simp(n,d),ticks=Array.from({length:d+1},(_,i)=>'<span class="nl-tick '+(i===n?'target':'')+'" style="left:'+(i/d*100)+'%"><i></i><b>'+(i===0?'0':i===d?'1':i===n?'?':'')+'</b>'+(i===n?'<em aria-hidden="true">▲</em>':'')+'</span>').join('');return{topic:'Number Line',prompt:'The line from 0 to 1 is split into '+d+' equal intervals. What fraction is shown by the blue marker?',html:'<div class="number-line-wrap"><div class="number-line" aria-label="Number line from zero to one split into '+d+' equal intervals; blue marker at interval '+n+'"><div class="nl-axis"></div>'+ticks+'</div><p class="visual-hint">Count the equal intervals from 0 to the blue marker.</p></div>',answer:ans,type:'fraction',solution:'The whole distance from 0 to 1 is divided into '+d+' equal intervals. The blue marker is '+n+' intervals from 0, so it represents '+n+'/'+d+', which simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function shareProblem(){const sets=[[[1,3],[1,6]],[[2,5],[1,5]],[[1,4],[1,8]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[1]*b[1]-a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:'A community garden uses '+a[0]+'/'+a[1]+' of its plots for vegetables and '+b[0]+'/'+b[1]+' for herbs. The rest is used for flowers. What fraction is used for flowers?',answer:ans,type:'fraction',strict:true,solution:'The whole garden is 1. Add the vegetable and herb shares, then subtract that amount from 1. The remaining share is '+ans[0]+'/'+ans[1]+'.'}}
function tankProblem(){const sets=[[[5,6],[1,3]],[[7,8],[1,4]],[[4,5],[1,5]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:"A water tank is "+a[0]+"/"+a[1]+" full. Water equal to "+b[0]+"/"+b[1]+" of the tank's total capacity is used. What fraction of the tank's total capacity remains?",answer:ans,type:'fraction',strict:true,solution:'Both fractions refer to the total tank capacity, so subtract the amount used from the amount present. The result simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function recipeProblem(){const sets=[[[5,2],[7,4]],[[9,4],[3,2]],[[7,3],[4,3]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:'A recipe needs '+a[0]+'/'+a[1]+' cups of flour, but only '+b[0]+'/'+b[1]+' cups are available. How many more cups are needed?',answer:ans,type:'fraction',strict:true,solution:'Subtract the amount available from the amount needed. After using a common denominator and simplifying, the shortage is '+ans[0]+'/'+ans[1]+' cups.'}}
function trailProblem(){const sets=[[[7,2],[5,4],[1,2]],[[15,4],[3,2],[3,4]],[[13,3],[5,3],[2,3]]],s=choice(sets),t=s[0],a=s[1],b=s[2],den=t[1]*a[1]*b[1],num=t[0]*a[1]*b[1]-a[0]*t[1]*b[1]-b[0]*t[1]*a[1],ans=simp(num,den);return{topic:'Multi-step Problem',prompt:'A walking trail is '+t[0]+'/'+t[1]+' km long. Maya walks '+a[0]+'/'+a[1]+' km before lunch and '+b[0]+'/'+b[1]+' km after lunch. How much of the trail remains?',answer:ans,type:'fraction',strict:true,solution:'First add the two distances Maya walked. Then subtract that total from the full trail length. The remaining distance is '+ans[0]+'/'+ans[1]+' km.'}}

function ribbonProblem(){const d=8,a=rnd(3,5),b=rnd(1,2),ans=simp(a-b,d);return{topic:'Measurement Problem',prompt:'A craft ribbon has '+a+'/'+d+' metre remaining. Priya uses '+b+'/'+d+' metre for a card. What fraction of a metre remains?',answer:ans,type:'fraction',strict:true,solution:'Both lengths are measured in eighths of a metre. Subtract the amount used from the amount remaining: '+a+'/'+d+' − '+b+'/'+d+' = '+ans[0]+'/'+ans[1]+'.'}}
function readingProblem(){const d=choice([6,8,10]),a=rnd(2,d-3),b=rnd(1,d-a-1),ans=simp(a+b,d);return{topic:'Reading Challenge',prompt:'On Monday, Noah reads '+a+'/'+d+' of a novel. On Tuesday, he reads another '+b+'/'+d+' of the same novel. What fraction of the novel has he read altogether?',answer:ans,type:'fraction',strict:true,solution:'The fractions describe the same whole book and already have the same denominator. Add the numerators and simplify: '+a+'/'+d+' + '+b+'/'+d+' = '+ans[0]+'/'+ans[1]+'.'}}
function classProjectProblem(){const a=choice([[1,3],[2,5],[3,8]]),b=choice([[1,6],[1,5],[1,8]]);if(a[0]*b[1]+b[0]*a[1]>=a[1]*b[1])return classProjectProblem();const ans=simp(a[1]*b[1]-a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Project Planning',prompt:'A class uses '+a[0]+'/'+a[1]+' of its display board for research and '+b[0]+'/'+b[1]+' for diagrams. The rest is reserved for conclusions. What fraction of the board is reserved for conclusions?',answer:ans,type:'fraction',strict:true,solution:'Treat the whole board as 1. Add the research and diagram sections, then subtract their total from 1. The remaining fraction is '+ans[0]+'/'+ans[1]+'.'}}
function juiceProblem(){const total=choice([[11,4],[13,4],[17,6]]),used=choice([[3,4],[5,6],[7,8]]),ans=simp(total[0]*used[1]-used[0]*total[1],total[1]*used[1]);return{topic:'Capacity Problem',prompt:'A jug contains '+total[0]+'/'+total[1]+' litres of juice. At lunch, '+used[0]+'/'+used[1]+' litre is served. How much juice remains?',answer:ans,type:'fraction',strict:true,solution:'Subtract the amount served from the amount in the jug. Rename the fractions with a common denominator, subtract, then simplify. The amount remaining is '+ans[0]+'/'+ans[1]+' litres.'}}
function compareJourneyProblem(){const pair=choice([[[3,4],[5,8]],[[5,6],[2,3]],[[7,8],[3,4]]]),a=pair[0],b=pair[1],cmp=a[0]*b[1]>b[0]*a[1]?'>':'<';return{topic:'Reasoning in Context',prompt:'Ava completes '+a[0]+'/'+a[1]+' of a cycling route. Ben completes '+b[0]+'/'+b[1]+' of the same route. Which comparison is correct?',html:expr([a,'___',b]),answer:cmp,type:'choice',options:['<','=','>'],solution:'Because both fractions describe the same route, compare their values using equivalent fractions or a number line. The correct symbol is '+cmp+'.'}}
function orderRelated(){const base=choice([6,8,10,12]),small=choice([2,3,4,5,6].filter(d=>d<base&&base%d===0));const vals=[];while(vals.length<3){const d=choice([small,base]),n=rnd(1,d-1),key=n/d;if(!vals.some(x=>Math.abs(x[0]/x[1]-key)<1e-9))vals.push([n,d])}const sorted=[...vals].sort((x,y)=>x[0]/x[1]-y[0]/y[1]);const answer=sorted.map(x=>x[0]+'/'+x[1]).join(' < ');const wrong1=[...sorted].reverse().map(x=>x[0]+'/'+x[1]).join(' < ');const wrong2=[sorted[1],sorted[0],sorted[2]].map(x=>x[0]+'/'+x[1]).join(' < ');const wrong3=[sorted[0],sorted[2],sorted[1]].map(x=>x[0]+'/'+x[1]).join(' < ');return{topic:'Order Fractions',prompt:'Which option shows these fractions from smallest to largest?',html:expr([vals[0],',',vals[1],',',vals[2]]),answer,type:'choice',options:shuffle([answer,wrong1,wrong2,wrong3]),solution:'Rename the fractions using a related common denominator or place them on a number line. Then order them from the smallest value to the largest.'}}
function missingRelated(){const pair=choice([[2,4],[2,6],[3,6],[4,8],[5,10],[6,12]]),d1=pair[0],d2=pair[1],a=rnd(1,d1-1),target=a*(d2/d1),b=rnd(1,d2-target),sum=target+b;return{topic:'Missing Fraction',prompt:'Find the missing numerator.',html:expr([[a,d1],'+',['?',d2],'=',[sum,d2]]),answer:b,type:'single',solution:'Rename the first fraction with denominator '+d2+'. Then find the numerator needed to make the total.'}}
function mixedSameAdd(){const d=choice([4,5,6,8]),w=choice([1,2]),a=rnd(1,d-2),b=rnd(1,d-a-1),sum=a+b;return{topic:'Mixed Numerals',prompt:'Add. Keep the answer as a mixed number.',html:expr([mixed(w,a,d),'+',[b,d]]),answer:[w,sum,d],type:'mixed',solution:'The fractional parts have the same denominator. Add their numerators and keep the whole-number part. Simplify the fraction if needed.'}}
function estimateReasonable(){const d=choice([6,8,10]),a=rnd(Math.ceil(d/2),d-1),b=rnd(1,Math.floor(d/3)),actual=(a+b)/d;const answer=actual<0.75?'less than 1':'about 1';return{topic:'Estimate First',prompt:'Before calculating exactly, which estimate is most reasonable?',html:expr([[a,d],'+',[b,d]]),answer,type:'choice',options:['less than 1','about 1','more than 2'],solution:'Use familiar benchmarks such as one half and one whole. The fractions together are '+answer+'. An estimate helps you check whether an exact answer makes sense.'}}
function reasoningError(){return{topic:'Reasoning',prompt:'A student has added the fractions incorrectly. Which statement best explains the error?',html:expr([[2,3],'+',[1,6],'=',[3,9]]),answer:'Rename the fractions with a common denominator before adding.',type:'choice',options:['Add the numerators and denominators separately.','Rename the fractions with a common denominator before adding.','Only add the denominators.','Every answer must have denominator 9.'],solution:'Denominators tell the size of the parts. Rename '+frac(2,3)+' as '+frac(4,6)+', then '+frac(4,6)+' + '+frac(1,6)+' = '+frac(5,6)+'.'}}
// Difficulty is controlled by the skill sequence, not merely by the label shown on screen.
// Randomisation happens only inside each five-question level.
const DIFFICULTY_BANDS=[
{level:'FOUNDATION',skills:[visualBar,numberLine,compare,equivalent,partitionQ]},
{level:'DEVELOPING',skills:[areaAdd,stripSubtract,()=>same('+'),()=>same('-'),simplifyQ]},
{level:'DEVELOPING +',skills:[improper,toImproper,compareMixed,compareRelated,orderRelated]},
{level:'PROFICIENT',skills:[()=>related('+'),()=>related('-'),numberLineAdd,missingRelated,mixedSameAdd]},
{level:'APPLICATION',skills:[ribbonProblem,readingProblem,shareProblem,compareJourneyProblem,estimateReasonable]},
{level:'CHALLENGE',skills:[reasoningError,tankProblem,classProjectProblem,triple,trailProblem]}
];
function buildQuiz(){const seen=new Set();return DIFFICULTY_BANDS.flatMap(b=>shuffle(b.skills.map(f=>{const q=unique(f,seen);q.level=b.level;return q})))}
let quiz=[],index=0,score=0,answered=false,attemptSaved=false;
const qn=document.getElementById('qNumber'),ql=document.getElementById('qLevel'),qs=document.getElementById('qScore'),qp=document.getElementById('quizProgress'),qt=document.getElementById('qTopic'),qprompt=document.getElementById('qPrompt'),qd=document.getElementById('qDisplay'),qa=document.getElementById('qAnswer'),qf=document.getElementById('qFeedback'),solution=document.getElementById('qSolution'),check=document.getElementById('checkAnswer'),next=document.getElementById('nextQuestion'),result=document.getElementById('resultCard');
function level(){return quiz[index]?.level||DIFFICULTY_BANDS[Math.min(Math.floor(index/5),DIFFICULTY_BANDS.length-1)].level}
function answerFieldName(part){return `mm-q${index+1}-${part}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function safeNumericInput(id,part,label,extraClass=''){return `<input id="${id}" name="${answerFieldName(part)}" class="number-input${extraClass?' '+extraClass:''}" inputmode="numeric" autocomplete="new-password" autocorrect="off" autocapitalize="off" spellcheck="false" aria-label="${label}" data-mm-answer="true">`}
function fractionEntry(){qa.innerHTML='<div class="fraction-entry">'+safeNumericInput('num','numerator','Numerator')+'<i></i>'+safeNumericInput('den','denominator','Denominator')+'</div>'}
function render(){const q=quiz[index];answered=false;qn.textContent=`${index+1} / ${TOTAL}`;ql.textContent=level();qs.textContent=`${score} / ${TOTAL}`;qp.style.width=`${((index+1)/TOTAL)*100}%`;qt.textContent=q.topic;qprompt.innerHTML=rich(q.prompt);qd.innerHTML=q.html?rich(q.html):expr(q.parts||[]);qf.textContent='';qf.className='q-feedback';solution.hidden=true;solution.innerHTML='';check.disabled=false;next.disabled=true;qa.innerHTML='';
if(q.type==='fraction')fractionEntry();else if(q.type==='single')qa.innerHTML=safeNumericInput('single','single','Answer','single-input');else if(q.type==='mixed')qa.innerHTML='<div class="mixed-entry"><label>Whole'+safeNumericInput('whole','whole','Whole number')+'</label><div class="fraction-entry">'+safeNumericInput('num','mixed-numerator','Numerator')+'<i></i>'+safeNumericInput('den','mixed-denominator','Denominator')+'</div></div>';else if(q.type==='choice')qa.innerHTML='<div class="choice-wrap">'+q.options.map((o,i)=>`<button type="button" data-choice-index="${i}">${richOption(o)}</button>`).join('')+'</div>';
qa.querySelectorAll('[data-choice-index]').forEach(b=>b.addEventListener('click',()=>checkChoice(q.options[Number(b.dataset.choiceIndex)])))}
function val(id){const e=document.getElementById(id);return e&&/^-?\d+$/.test(e.value.trim())?Number(e.value):null}
function finishCheck(ok,answer){answered=true;const x=quiz[index];if(ok){score++;qf.textContent='Correct!';qf.className='q-feedback correct'}else{qf.textContent='Not quite. Read the worked solution below.';qf.className='q-feedback incorrect';solution.hidden=false;solution.innerHTML='<h4>Worked solution</h4><p>'+rich(x.solution||'Review the fraction strategy used in this question.')+'</p><p><strong>Answer: '+rich(answer)+'</strong></p>'}qs.textContent=`${score} / ${TOTAL}`;check.disabled=true;next.disabled=false;qa.querySelectorAll('input,button').forEach(x=>x.disabled=true)}
function checkChoice(v){if(answered)return;finishCheck(v===quiz[index].answer,quiz[index].answer)}
check.addEventListener('click',()=>{if(answered)return;const q=quiz[index];if(q.type==='choice'){qf.textContent='Choose one of the answer options.';return}if(q.type==='single'){const v=val('single');if(v===null){qf.textContent='Enter a whole number.';return}finishCheck(v===q.answer,String(q.answer));return}if(q.type==='mixed'){const w=val('whole'),n=val('num'),d=val('den');if([w,n,d].some(v=>v===null)||d===0){qf.textContent='Complete all three boxes.';return}finishCheck(w===q.answer[0]&&eq([n,d],[q.answer[1],q.answer[2]]),mixed(...q.answer));return}const n=val('num'),d=val('den');if(n===null||d===null||d===0){qf.textContent='Complete the numerator and denominator.';return}const equivalent=eq([n,d],q.answer),exact=n===q.answer[0]&&d===q.answer[1];if(q.strict&&equivalent&&!exact){qf.textContent='Equivalent, but simplify it fully.';qf.className='q-feedback incorrect';return}finishCheck(q.strict?exact:equivalent,frac(...q.answer))});
next.addEventListener('click',()=>{if(index<TOTAL-1){index++;render()}else finish()});document.getElementById('restartQuiz').addEventListener('click',startQuiz);
function startQuiz(){quiz=buildQuiz();index=0;score=0;attemptSaved=false;document.querySelector('.quiz-card').hidden=false;result.hidden=true;render()}
async function finish(){document.querySelector('.quiz-card').hidden=true;result.hidden=false;const pct=Math.round((score/TOTAL)*100);const msg=score===TOTAL?'Perfect score — proficiency achieved!':pct>=85?'Excellent understanding.':pct>=70?'Strong work. Review any concepts you missed.':pct>=50?'Good progress. Revisit the learning pages before another attempt.':'Revisit Pages 1–5, then try the challenge again.';result.innerHTML=`<p class="tag">CHALLENGE COMPLETE</p><h2>${pct}%</h2><strong>${score} out of ${TOTAL} correct</strong><p>${msg}</p><p id="saveStatus">Recording completed attempt…</p>`;if(attemptSaved)return;attemptSaved=true;const status=document.getElementById('saveStatus');try{let tries=0;while(!window.MathMagicFractionsProgress?.saveAttempt&&tries<20){await new Promise(r=>setTimeout(r,100));tries++}if(!window.MathMagicFractionsProgress?.saveAttempt)throw new Error('Progress service unavailable');const p=await window.MathMagicFractionsProgress.saveAttempt(score);if(status)status.textContent=`✓ Attempt recorded • ${Math.min(p.attempts,5)}/5 completed • Best ${p.bestScore}/${TOTAL}${p.proficient?' • PROFICIENT':''}`;}catch(e){console.error('Progress save failed:',e);attemptSaved=false;if(status){status.textContent='This attempt could not be recorded. Please keep this page open and try again.';status.className='incorrect'}}}
