'use strict';
const TOTAL=30;
const screens=[...document.querySelectorAll('.screen')],tabs=[...document.querySelectorAll('.tab')];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='challenge'&&!quiz.length)startQuiz()}
tabs.forEach(t=>t.addEventListener('click',()=>showScreen(t.dataset.screen)));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.next)));
document.querySelectorAll('[data-practice]').forEach(b=>b.addEventListener('click',()=>{b.nextElementSibling.textContent='Answer: '+b.dataset.practice}));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,choice=a=>a[rnd(0,a.length-1)];
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)||1}function simp(n,d){const g=gcd(n,d);return[n/g,d/g]}function eq(a,b){return a[0]*b[1]===b[0]*a[1]}
function frac(n,d){return `<span class="frac"><span>${n}</span><i></i><span>${d}</span></span>`}function mixed(w,n,d){return `<span class="mixed"><strong>${w}</strong>${frac(n,d)}</span>`}
function expr(parts){return '<div class="math-row">'+parts.map(x=>Array.isArray(x)?frac(x[0],x[1]):x).join('')+'</div>'}
function same(op='+'){const d=choice([4,5,6,7,8,9,10,12]);let a=rnd(1,d-2),b=rnd(1,d-2);if(op==='-'&&b>=a)[a,b]=[Math.max(a,b),Math.min(a,b)];if(op==='-'&&a===b)a=Math.min(d-1,a+1);const ans=simp(op==='+'?a+b:a-b,d);return{topic:'Same Denominators',prompt:op==='+'?'Add and simplify.':'Subtract and simplify.',parts:[[a,d],op,[b,d]],answer:ans,type:'fraction'}}
function equivalent(){const d=choice([3,4,5,6,8]),n=rnd(1,d-1),m=rnd(2,4);return{topic:'Equivalent Fractions',prompt:'Find the missing numerator.',parts:[[n,d],'=',['?',d*m]],answer:n*m,type:'single'}}
function simplifyQ(){const d=choice([3,4,5,6,8]),n=rnd(1,d-1),m=rnd(2,5);return{topic:'Simplifying',prompt:'Write this fraction in simplest form.',parts:[[n*m,d*m]],answer:simp(n*m,d*m),type:'fraction',strict:true}}
function compare(){const d=choice([4,5,6,8,10]),a=rnd(1,d-1),b=rnd(1,d-1);return{topic:'Compare Fractions',prompt:'Choose the correct symbol.',parts:[[a,d],'___',[b,d]],answer:a>b?'>':a<b?'<':'=',type:'choice',options:['<','=','>']}}
function related(op='+'){const pair=choice([[2,4],[2,6],[3,6],[4,8],[5,10],[6,12]]),d1=pair[0],d2=pair[1];let a=rnd(1,d1-1),b=rnd(1,d2-1);if(op==='-'&&a/d1<=b/d2){a=d1-1;b=1}const n=op==='+'?a*d2+b*d1:a*d2-b*d1;return{topic:'Related Denominators',prompt:(op==='+'?'Add':'Subtract')+' and simplify.',parts:[[a,d1],op,[b,d2]],answer:simp(n,d1*d2),type:'fraction',strict:true}}
function improper(){const d=choice([3,4,5,6]),w=rnd(1,3),r=rnd(1,d-1),s=simp(r,d),n=w*s[1]+s[0];return{topic:'Mixed Numbers',prompt:'Change this improper fraction to a mixed number.',parts:[[n,s[1]]],answer:[w,s[0],s[1]],type:'mixed'}}
function toImproper(){const d=choice([3,4,5,6]),w=rnd(1,3),n=rnd(1,d-1),s=simp(n,d);return{topic:'Mixed Numbers',prompt:'Change this mixed number to an improper fraction.',html:expr([mixed(w,s[0],s[1])]),answer:[w*s[1]+s[0],s[1]],type:'fraction'}}
function triple(){const base=choice([6,8,10,12]),divs=[2,3,4,5,6].filter(x=>x<base&&base%x===0),d1=choice(divs),d2=base,d3=base;const a=rnd(1,d1-1),b=rnd(1,Math.max(1,base-3)),c=rnd(1,Math.min(2,base-1));let n=a*(base/d1)+b-c;if(n<=0)n=a*(base/d1)+b;return{topic:'Multi-step Fractions',prompt:'Calculate from left to right. Rename the fractions with a common denominator, then simplify your final answer.',parts:[[a,d1],'+',[b,d2],'−',[c,d3]],answer:simp(n,base),type:'fraction',strict:true}}
function wordProblem(){return{topic:'Problem Solving',prompt:'A recipe uses 1/2 cup of oats and 1/4 cup of nuts. How much is used altogether?',parts:[[1,2],'+',[1,4]],answer:[3,4],type:'fraction'}}
function visualBar(){const d=choice([6,8,10,12]),n=rnd(2,d-2),ans=simp(n,d),cells=Array.from({length:d},(_,i)=>'<span class="bar-cell '+(i<n?'filled':'')+'"></span>').join('');return{topic:'Visual Fractions',prompt:'The bar represents one whole. What fraction is shaded? Give your answer in simplest form.',html:'<div class="fraction-visual" aria-label="'+n+' of '+d+' equal parts shaded">'+cells+'</div>',answer:ans,type:'fraction',strict:true,solution:'Count the equal parts: '+n+' of '+d+' are shaded. This is '+n+'/'+d+'. Simplify to '+ans[0]+'/'+ans[1]+'.'}}
function numberLine(){const d=choice([4,5,6,8]),n=rnd(1,d-1),ans=simp(n,d),ticks=Array.from({length:d+1},(_,i)=>'<span class="tick '+(i===n?'target':'')+'"><i></i><b>'+(i===0?'0':i===d?'1':i===n?'?':'')+'</b></span>').join('');return{topic:'Number Line',prompt:'The interval from 0 to 1 is divided into equal parts. What fraction is marked?',html:'<div class="number-line" aria-label="Number line divided into '+d+' equal intervals">'+ticks+'</div>',answer:ans,type:'fraction',solution:'There are '+d+' equal intervals from 0 to 1. The marked point is '+n+' intervals from 0, so it is '+n+'/'+d+', which simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function shareProblem(){const sets=[[[1,3],[1,4]],[[2,5],[1,5]],[[1,4],[1,6]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[1]*b[1]-a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:'A community garden uses '+a[0]+'/'+a[1]+' of its plots for vegetables and '+b[0]+'/'+b[1]+' for herbs. The rest is used for flowers. What fraction is used for flowers?',answer:ans,type:'fraction',strict:true,solution:'The whole garden is 1. Add the vegetable and herb shares, then subtract that amount from 1. The remaining share is '+ans[0]+'/'+ans[1]+'.'}}
function tankProblem(){const sets=[[[5,6],[1,4]],[[7,8],[1,4]],[[4,5],[1,5]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:"A water tank is "+a[0]+"/"+a[1]+" full. Water equal to "+b[0]+"/"+b[1]+" of the tank's total capacity is used. What fraction of the tank's total capacity remains?",answer:ans,type:'fraction',strict:true,solution:'Both fractions refer to the total tank capacity, so subtract the amount used from the amount present. The result simplifies to '+ans[0]+'/'+ans[1]+'.'}}
function recipeProblem(){const sets=[[[5,2],[7,4]],[[9,4],[5,3]],[[7,3],[3,2]]],s=choice(sets),a=s[0],b=s[1],ans=simp(a[0]*b[1]-b[0]*a[1],a[1]*b[1]);return{topic:'Problem Solving',prompt:'A recipe needs '+a[0]+'/'+a[1]+' cups of flour, but only '+b[0]+'/'+b[1]+' cups are available. How many more cups are needed?',answer:ans,type:'fraction',strict:true,solution:'Subtract the amount available from the amount needed. After using a common denominator and simplifying, the shortage is '+ans[0]+'/'+ans[1]+' cups.'}}
function trailProblem(){const sets=[[[7,2],[5,4],[2,3]],[[15,4],[3,2],[3,4]],[[13,3],[7,4],[5,6]]],s=choice(sets),t=s[0],a=s[1],b=s[2],den=t[1]*a[1]*b[1],num=t[0]*a[1]*b[1]-a[0]*t[1]*b[1]-b[0]*t[1]*a[1],ans=simp(num,den);return{topic:'Multi-step Problem',prompt:'A walking trail is '+t[0]+'/'+t[1]+' km long. Maya walks '+a[0]+'/'+a[1]+' km before lunch and '+b[0]+'/'+b[1]+' km after lunch. How much of the trail remains?',answer:ans,type:'fraction',strict:true,solution:'First add the two distances Maya walked. Then subtract that total from the full trail length. The remaining distance is '+ans[0]+'/'+ans[1]+' km.'}}
function reasoningError(){return{topic:'Reasoning',prompt:'A student says 2/3 + 1/6 = 3/9. Which statement best explains the error?',answer:'Rename the fractions with a common denominator before adding.',type:'choice',options:['Add the numerators and denominators separately.','Rename the fractions with a common denominator before adding.','Only add the denominators.','Every answer must have denominator 9.'],solution:'Denominators tell the size of the parts. Rename 2/3 as 4/6, then 4/6 + 1/6 = 5/6.'}}
function buildQuiz(){return[visualBar(),equivalent(),simplifyQ(),compare(),numberLine(),same('+'),same('-'),improper(),toImproper(),related('+'),related('-'),simplifyQ(),related('+'),improper(),reasoningError(),triple(),triple(),related('-'),toImproper(),triple(),shareProblem(),tankProblem(),recipeProblem(),trailProblem(),shareProblem(),visualBar(),numberLine(),tankProblem(),recipeProblem(),trailProblem()]}
let quiz=[],index=0,score=0,answered=false,attemptSaved=false;
const qn=document.getElementById('qNumber'),ql=document.getElementById('qLevel'),qs=document.getElementById('qScore'),qp=document.getElementById('quizProgress'),qt=document.getElementById('qTopic'),qprompt=document.getElementById('qPrompt'),qd=document.getElementById('qDisplay'),qa=document.getElementById('qAnswer'),qf=document.getElementById('qFeedback'),solution=document.getElementById('qSolution'),check=document.getElementById('checkAnswer'),next=document.getElementById('nextQuestion'),result=document.getElementById('resultCard');
function level(){return index<5?'FOUNDATION':index<10?'DEVELOPING':index<15?'DEVELOPING +':index<20?'PROFICIENT':index<25?'APPLICATION':'CHALLENGE'}
function fractionEntry(){qa.innerHTML='<div class="fraction-entry"><input id="num" class="number-input" inputmode="numeric" aria-label="Numerator"><i></i><input id="den" class="number-input" inputmode="numeric" aria-label="Denominator"></div>'}
function render(){const q=quiz[index];answered=false;qn.textContent=`${index+1} / ${TOTAL}`;ql.textContent=level();qs.textContent=`${score} / ${TOTAL}`;qp.style.width=`${((index+1)/TOTAL)*100}%`;qt.textContent=q.topic;qprompt.textContent=q.prompt;qd.innerHTML=q.html||expr(q.parts||[]);qf.textContent='';qf.className='q-feedback';solution.hidden=true;solution.innerHTML='';check.disabled=false;next.disabled=true;qa.innerHTML='';
if(q.type==='fraction')fractionEntry();else if(q.type==='single')qa.innerHTML='<input id="single" class="number-input single-input" inputmode="numeric">';else if(q.type==='mixed')qa.innerHTML='<div class="mixed-entry"><label>Whole<input id="whole" class="number-input" inputmode="numeric"></label><div class="fraction-entry"><input id="num" class="number-input" inputmode="numeric"><i></i><input id="den" class="number-input" inputmode="numeric"></div></div>';else if(q.type==='choice')qa.innerHTML='<div class="choice-wrap">'+q.options.map(o=>`<button type="button" data-choice="${o}">${o}</button>`).join('')+'</div>';
qa.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>checkChoice(b.dataset.choice)))}
function val(id){const e=document.getElementById(id);return e&&/^-?\d+$/.test(e.value.trim())?Number(e.value):null}
function finishCheck(ok,answer){answered=true;const x=quiz[index];if(ok){score++;qf.textContent='Correct!';qf.className='q-feedback correct'}else{qf.textContent='Not quite. Read the worked solution below.';qf.className='q-feedback incorrect';solution.hidden=false;solution.innerHTML='<h4>Worked solution</h4><p>'+(x.solution||'Review the fraction strategy used in this question.')+'</p><p><strong>Answer: '+answer+'</strong></p>'}qs.textContent=`${score} / ${TOTAL}`;check.disabled=true;next.disabled=false;qa.querySelectorAll('input,button').forEach(x=>x.disabled=true)}
function checkChoice(v){if(answered)return;finishCheck(v===quiz[index].answer,quiz[index].answer)}
check.addEventListener('click',()=>{if(answered)return;const q=quiz[index];if(q.type==='choice'){qf.textContent='Choose one of the symbols.';return}if(q.type==='single'){const v=val('single');if(v===null){qf.textContent='Enter a whole number.';return}finishCheck(v===q.answer,String(q.answer));return}if(q.type==='mixed'){const w=val('whole'),n=val('num'),d=val('den');if([w,n,d].some(v=>v===null)||d===0){qf.textContent='Complete all three boxes.';return}finishCheck(w===q.answer[0]&&eq([n,d],[q.answer[1],q.answer[2]]),mixed(...q.answer));return}const n=val('num'),d=val('den');if(n===null||d===null||d===0){qf.textContent='Complete the numerator and denominator.';return}const equivalent=eq([n,d],q.answer),exact=n===q.answer[0]&&d===q.answer[1];if(q.strict&&equivalent&&!exact){qf.textContent='Equivalent, but simplify it fully.';qf.className='q-feedback incorrect';return}finishCheck(q.strict?exact:equivalent,frac(...q.answer))});
next.addEventListener('click',()=>{if(index<TOTAL-1){index++;render()}else finish()});document.getElementById('restartQuiz').addEventListener('click',startQuiz);
function startQuiz(){quiz=buildQuiz();index=0;score=0;attemptSaved=false;document.querySelector('.quiz-card').hidden=false;result.hidden=true;render()}
async function finish(){document.querySelector('.quiz-card').hidden=true;result.hidden=false;const pct=Math.round((score/TOTAL)*100);const msg=score===TOTAL?'Perfect score — proficiency achieved!':pct>=85?'Excellent understanding.':pct>=70?'Strong work. Review any concepts you missed.':pct>=50?'Good progress. Revisit the learning pages before another attempt.':'Revisit Pages 1–5, then try the challenge again.';result.innerHTML=`<p class="tag">CHALLENGE COMPLETE</p><h2>${pct}%</h2><strong>${score} out of ${TOTAL} correct</strong><p>${msg}</p><p id="saveStatus">Recording completed attempt…</p>`;if(attemptSaved)return;attemptSaved=true;const status=document.getElementById('saveStatus');try{let tries=0;while(!window.MathMagicFractionsProgress?.saveAttempt&&tries<20){await new Promise(r=>setTimeout(r,100));tries++}if(!window.MathMagicFractionsProgress?.saveAttempt)throw new Error('Progress service unavailable');const p=await window.MathMagicFractionsProgress.saveAttempt(score);if(status)status.textContent=`✓ Attempt recorded • ${Math.min(p.attempts,5)}/5 completed • Best ${p.bestScore}/${TOTAL}${p.proficient?' • PROFICIENT':''}`;}catch(e){console.error('Progress save failed:',e);attemptSaved=false;if(status){status.textContent='This attempt could not be recorded. Please keep this page open and try again.';status.className='incorrect'}}}
