const screens=[...document.querySelectorAll('.screen')],tabs=[...document.querySelectorAll('.tab')];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='challenge'&&!quiz.length)startQuiz()}
tabs.forEach(t=>t.addEventListener('click',()=>showScreen(t.dataset.screen)));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.next)));
document.querySelectorAll('.practice button[data-answer]').forEach(btn=>btn.addEventListener('click',()=>{const box=btn.closest('.practice'),input=box.querySelector('input'),fb=box.querySelector('.practice-feedback');let value=input.value.trim().replace(/,/g,'');const target=btn.dataset.answer;const ok=value===target;fb.textContent=ok?'Correct — well done.':'Not quite. Look back at the example and try again.';fb.className='practice-feedback '+(ok?'correct':'incorrect')}));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,fmt=n=>n.toLocaleString('en-AU');
function placeQuestion(){const places=[10,100,1000,10000,100000],p=places[rnd(0,4)],digit=rnd(1,9),other=rnd(10000,899999),n=Math.floor(other/(p*10))*(p*10)+digit*p+(other%p);const raw=String(n),idx=raw.length-1-Math.log10(p);return{topic:'Place Value',prompt:'What is the value of the highlighted digit?',display:fmt(n),highlightIndex:idx,highlightDigit:digit,answer:String(digit*p),type:'number'}}
function digitPlaceQuestion(){const labels=[[1,'ones'],[10,'tens'],[100,'hundreds'],[1000,'thousands'],[10000,'ten thousands'],[100000,'hundred thousands']],x=labels[rnd(1,5)],p=x[0],digit=rnd(1,9),n=rnd(100000,999999);const fixed=Math.floor(n/(p*10))*(p*10)+digit*p+(n%p);return{topic:'Place Value',prompt:`Which place is the digit ${digit} in?`,display:fmt(fixed),answer:x[1],type:'select',options:['tens','hundreds','thousands','ten thousands','hundred thousands']}}
function expandedQuestion(){const n=rnd(100000,999999),parts=[];[100000,10000,1000,100,10,1].forEach(p=>{const d=Math.floor(n/p)%10;if(d)parts.push(fmt(d*p))});return{topic:'Representing Numbers',prompt:'Write this expanded form as a number.',display:parts.join(' + '),answer:String(n),type:'number'}}
function expandValueQuestion(){const n=rnd(100000,999999),p=[100,1000,10000][rnd(0,2)],d=Math.floor(n/p)%10;return{topic:'Representing Numbers',prompt:`In ${fmt(n)}, how much does the digit ${d} contribute to the number?`,display:'Enter its value',answer:String(d*p),type:'number'}}
function compareQuestion(){let a=rnd(10000,999999),b=rnd(10000,999999);if(a===b)b++;return{topic:'Compare & Order',prompt:'Choose the correct symbol.',display:`${fmt(a)}  ___  ${fmt(b)}`,answer:a>b?'>':'<',type:'select',options:['<','>','=']}}
function orderQuestion(){const nums=[rnd(10000,999999),rnd(10000,999999),rnd(10000,999999)];const asc=[...nums].sort((a,b)=>a-b);return{topic:'Compare & Order',prompt:'Which number is the smallest?',display:nums.map(fmt).join('   •   '),answer:String(asc[0]),type:'number'}}
function roundingQuestion(){const p=[10,100,1000,10000][rnd(0,3)],labels={10:'ten',100:'hundred',1000:'thousand',10000:'ten thousand'},n=rnd(10000,999999),ans=Math.round(n/p)*p;return{topic:'Rounding & Estimation',prompt:`Round ${fmt(n)} to the nearest ${labels[p]}.`,display:'',answer:String(ans),type:'number'}}
function estimateQuestion(){const a=rnd(12000,89000),b=rnd(12000,89000),ans=Math.round(a/10000)*10000+Math.round(b/10000)*10000;return{topic:'Rounding & Estimation',prompt:'Estimate the sum by rounding each number to the nearest ten thousand.',display:`${fmt(a)} + ${fmt(b)}`,answer:String(ans),type:'number'}}
function reasoningQuestion(i){const set=[
{topic:'Reasoning',prompt:'A number has 6 in the hundred-thousands place, 3 in the thousands place, 8 in the tens place and 2 in the ones place. All other digits are zero. What is the number?',display:'',answer:'603082',type:'number'},
{topic:'Reasoning',prompt:'Which number would round to 450,000 to the nearest ten thousand?',display:'Choose one',answer:'447200',type:'select',options:['443,900','447,200','455,100','461,000']},
{topic:'Reasoning',prompt:'A student says 398,950 is greater than 400,012 because 950 is greater than 012. Which number is actually greater?',display:'',answer:'400012',type:'number'},
{topic:'Reasoning',prompt:'A stadium attendance was 248,761. About how many people is this to the nearest ten thousand?',display:'',answer:'250000',type:'number'},
{topic:'Reasoning',prompt:'What number is 10 times 42,506?',display:'Think about how every digit changes place.',answer:'425060',type:'number'}];return set[i%set.length]}
function buildQuiz(){return[placeQuestion(),digitPlaceQuestion(),expandedQuestion(),compareQuestion(),roundingQuestion(),placeQuestion(),expandedQuestion(),orderQuestion(),roundingQuestion(),compareQuestion(),expandValueQuestion(),orderQuestion(),roundingQuestion(),estimateQuestion(),compareQuestion(),reasoningQuestion(0),reasoningQuestion(1),reasoningQuestion(2),reasoningQuestion(3),reasoningQuestion(4)]}
let quiz=[],index=0,score=0,answered=false;const qn=document.getElementById('qNumber'),ql=document.getElementById('qLevel'),qs=document.getElementById('qScore'),qp=document.getElementById('quizProgress'),qt=document.getElementById('qTopic'),qprompt=document.getElementById('qPrompt'),qd=document.getElementById('qDisplay'),qa=document.getElementById('qAnswer'),qf=document.getElementById('qFeedback'),check=document.getElementById('checkAnswer'),next=document.getElementById('nextQuestion'),result=document.getElementById('resultCard');
function level(){return index<5?'FOUNDATION':index<10?'DEVELOPING':index<15?'PROFICIENT':'CHALLENGE'}
function render(){const q=quiz[index];answered=false;qn.textContent=`${index+1} / 20`;ql.textContent=level();qs.textContent=`${score} / 20`;qp.style.width=`${((index+1)/20)*100}%`;qt.textContent=q.topic;qprompt.textContent=q.prompt;if(Number.isInteger(q.highlightIndex)){const raw=String(q.display).replace(/,/g,'');qd.innerHTML='';[...raw].forEach((ch,i)=>{if(i>0&&(raw.length-i)%3===0)qd.append(document.createTextNode(','));const span=document.createElement('span');span.textContent=ch;if(i===q.highlightIndex){span.className='highlight-digit';span.setAttribute('aria-label',ch+' highlighted')}qd.append(span)})}else{qd.textContent=q.display}qf.textContent='';qf.className='q-feedback';check.disabled=false;next.disabled=true;qa.innerHTML='';if(q.type==='select'){const s=document.createElement('select');s.innerHTML='<option value="">Choose an answer</option>'+q.options.map(o=>`<option value="${o.replace(/,/g,'')}">${o}</option>`).join('');qa.appendChild(s)}else{const input=document.createElement('input');input.inputMode='numeric';input.placeholder='Your answer';qa.appendChild(input);input.focus()}}
function normal(v){return String(v).trim().toLowerCase().replace(/,/g,'').replace(/-/g,' ')}
check.addEventListener('click',()=>{if(answered)return;const field=qa.querySelector('input,select');if(!field||!field.value.trim()){qf.textContent='Enter or choose an answer first.';return}answered=true;const ok=normal(field.value)===normal(quiz[index].answer);if(ok){score++;qf.textContent='Correct!';qf.className='q-feedback correct'}else{const shown=quiz[index].type==='number'&&!isNaN(Number(quiz[index].answer))?fmt(Number(quiz[index].answer)):quiz[index].answer;qf.textContent=`Not quite. The answer is ${shown}. Review ${quiz[index].topic} if you need another look.`;qf.className='q-feedback incorrect'}qs.textContent=`${score} / 20`;check.disabled=true;next.disabled=false});
next.addEventListener('click',()=>{if(index<19){index++;render()}else finish()});
function finish(){document.querySelector('.quiz-card').hidden=true;result.hidden=false;const pct=score*5;let msg=pct>=85?'Excellent understanding.':pct>=70?'Strong work. Review any concepts you missed.':pct>=50?'Good progress. Revisit the learning pages before another attempt.':'Revisit Pages 1–4, then try the challenge again.';result.innerHTML=`<p class="page-tag">CHALLENGE COMPLETE</p><h2>${pct}%</h2><strong>${score} out of 20 correct</strong><p>${msg}</p>`}
function startQuiz(){quiz=buildQuiz();index=0;score=0;document.querySelector('.quiz-card').hidden=false;result.hidden=true;render()}
document.getElementById('restartQuiz').addEventListener('click',startQuiz);qa?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!check.disabled)check.click()});
