'use strict';
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore}=require('firebase-admin/firestore');
const crypto=require('crypto');
initializeApp();
const db=getFirestore(),TOTAL=30;
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,choice=a=>a[rnd(0,a.length-1)];
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)||1} function simp(n,d){const g=gcd(n,d);return[n/g,d/g]}
function same(op='+'){const d=choice([4,5,6,8,10,12]);let a=rnd(1,d-2),b=rnd(1,d-2);if(op==='-'&&b>=a)[a,b]=[Math.max(a,b),Math.min(a,b)];return{topic:'Same Denominators',prompt:op==='+'?'Add and simplify.':'Subtract and simplify.',parts:[[a,d],op,[b,d]],answer:simp(op==='+'?a+b:a-b,d),type:'fraction',strict:true,solution:'Work with the numerators because the parts are the same size, then simplify.'}}
function equivalent(){const d=choice([3,4,5,6,8]),n=rnd(1,d-1),m=rnd(2,4);return{topic:'Equivalent Fractions',prompt:'Find the missing numerator.',parts:[[n,d],'=',['?',d*m]],answer:n*m,type:'single',solution:'Multiply the numerator and denominator by the same factor.'}}
function compare(){const d=choice([4,5,6,8,10]),a=rnd(1,d-1),b=rnd(1,d-1);return{topic:'Compare Fractions',prompt:'Choose the correct symbol.',parts:[[a,d],'___',[b,d]],answer:a>b?'>':a<b?'<':'=',type:'choice',options:['<','=','>'],solution:'With equal denominators, compare the numerators.'}}
function related(op='+'){const pair=choice([[2,4],[2,6],[3,6],[4,8],[5,10],[6,12]]),d1=pair[0],d2=pair[1];let a=rnd(1,d1-1),b=rnd(1,d2-1);if(op==='-'&&a/d1<=b/d2){a=d1-1;b=1}const n=op==='+'?a*(d2/d1)+b:a*(d2/d1)-b;return{topic:'Related Denominators',prompt:(op==='+'?'Add':'Subtract')+' and simplify.',parts:[[a,d1],op,[b,d2]],answer:simp(n,d2),type:'fraction',strict:true,solution:'Rename using the larger related denominator, calculate, then simplify.'}}
function visual(){const d=choice([6,8,10,12]),n=rnd(2,d-2);return{topic:'Visual Fractions',prompt:'The bar represents one whole. What fraction is shaded? Give your answer in simplest form.',visual:{kind:'bar',parts:d,filled:n},answer:simp(n,d),type:'fraction',strict:true,solution:'Count the shaded equal parts and simplify.'}}
function numberLine(){const d=choice([4,5,6,8]),n=rnd(1,d-1);return{topic:'Number Line',prompt:'What fraction is shown by the marker?',visual:{kind:'numberLine',parts:d,marker:n},answer:simp(n,d),type:'fraction',solution:'Count equal intervals from 0 to the marker.'}}
function improper(){const d=choice([3,4,5,6]),w=rnd(1,3),r=rnd(1,d-1);return{topic:'Mixed Numbers',prompt:'Change this improper fraction to a mixed number.',parts:[[w*d+r,d]],answer:[w,r,d],type:'mixed',solution:'Divide the numerator by the denominator.'}}
function word(){const set=choice([[[1,2],[1,4]],[[1,3],[1,6]],[[2,5],[1,5]]]),a=set[0],b=set[1],den=b[1],ans=simp(a[0]*(den/a[1])+b[0],den);return{topic:'Problem Solving',prompt:'A class uses '+a[0]+'/'+a[1]+' of a display for research and '+b[0]+'/'+b[1]+' for diagrams. What fraction is used altogether?',answer:ans,type:'fraction',strict:true,solution:'Rename the related fractions, add, then simplify.'}}
const bands=[['FOUNDATION',[visual,numberLine,compare,equivalent,visual]],['DEVELOPING',[()=>same('+'),()=>same('-'),equivalent,compare,()=>same('+')]],['DEVELOPING +',[improper,compare,equivalent,numberLine,improper]],['PROFICIENT',[()=>related('+'),()=>related('-'),()=>same('+'),()=>same('-'),()=>related('+')]],['APPLICATION',[word,()=>related('+'),word,()=>related('-'),word]],['CHALLENGE',[()=>related('+'),()=>related('-'),word,()=>same('+'),()=>same('-')]]];
function build(){return bands.flatMap(([level,fs])=>fs.map(f=>({...f(),level}))).slice(0,TOTAL)}
function publicQ(q,i){const {answer,solution,...safe}=q;return{...safe,index:i+1,total:TOTAL}}
async function approved(uid){const s=await db.doc('access/'+uid).get();return s.exists&&s.data().approved===true}
exports.startFractionsChallenge=onCall({enforceAppCheck:true},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in required.');if(!(await approved(req.auth.uid)))throw new HttpsError('permission-denied','MathMagic approval required.');const qs=build(),id=crypto.randomUUID(),answers=qs.map(q=>({answer:q.answer,solution:q.solution,type:q.type,strict:!!q.strict}));await db.doc('challengeSessions/'+id).set({uid:req.auth.uid,topic:'fractions',answers,createdAt:Date.now(),nextIndex:0,score:0,complete:false});return{sessionId:id,question:publicQ(qs[0],0)};});
exports.submitFractionsAnswer=onCall({enforceAppCheck:true},async req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in required.');const id=String(req.data?.sessionId||''),index=Number(req.data?.index),response=req.data?.response;if(!id)throw new HttpsError('invalid-argument','Missing session.');const ref=db.doc('challengeSessions/'+id);return db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Session expired.');const d=s.data();if(d.uid!==req.auth.uid)throw new HttpsError('permission-denied','Wrong session owner.');if(d.complete||index!==d.nextIndex)throw new HttpsError('failed-precondition','Question is not current.');const key=d.answers[index],eq=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((v,i)=>Number(v)===Number(b[i]));let ok=false;if(key.type==='choice'||key.type==='single')ok=String(response)===String(key.answer);else if(Array.isArray(response)&&Array.isArray(key.answer)){if(key.type==='fraction'&&response.length===2){const n=response[0],den=response[1],an=key.answer[0],ad=key.answer[1];ok=Number(den)!==0&&Number(n)*Number(ad)===Number(an)*Number(den);if(key.strict)ok=ok&&Number(n)===Number(an)&&Number(den)===Number(ad)}else ok=eq(response,key.answer)}const score=d.score+(ok?1:0),next=index+1,complete=next>=TOTAL;tx.update(ref,{score,nextIndex:next,complete});return{correct:ok,solution:ok?null:key.solution,answer:ok?null:key.answer,score,complete,nextIndex:next};});});
