const{test,expect}=require('@playwright/test');
const levels=['FOUNDATION','DEVELOPING','DEVELOPING +','PROFICIENT','APPLICATION','CHALLENGE'];
function questions(){return Array.from({length:30},(_,i)=>({index:i+1,total:30,level:levels[Math.floor(i/5)],topic:i%5===4?'Divisibility reasoning':i%3===0?'Factors':'Multiples',prompt:i%5===4?'Which statement is correct?':'Solve this Year 5 factors and multiples question.',display:i%5===4?'42 is divisible by 6.':'6 × 7 = 42',type:i%5===4?'choice':'number',...(i%5===4?{options:['Yes','No','Always false','Not enough information']}:{})}))}
async function open(page){const qs=questions();await page.addInitScript(qs=>{let pos=0;window.MathMagicFactorsMultiplesProtected={start:async()=>({sessionId:'ci-session',question:qs[0]}),submit:async(_s,i,response)=>{const correct=i%5===4?response==='Yes':String(response)==='42';pos=i+1;return{correct,solution:'Use factors, multiples and divisibility rules.',score:0,complete:pos>=30,nextIndex:pos,question:pos<30?qs[pos]:null}};window.MathMagicFactorsMultiplesProgress={saveAttempt:async score=>({bestScore:score})}},qs);await page.route('**/js/factors-multiples-auth.js*',r=>r.abort());await page.goto('/factors-multiples.html');await page.evaluate(()=>document.body.classList.remove('auth-loading'))}
test('five lessons and challenge navigate',async({page})=>{await open(page);for(const id of ['lesson1','lesson2','lesson3','lesson4','lesson5','challenge']){await page.locator('[data-screen="'+id+'"]').click();await expect(page.locator('#'+id)).toHaveClass(/active/)}})
test('protected adapter completes all 30 positions with number and unique choice controls',async({page})=>{await open(page);await page.locator('[data-screen="challenge"]').click();for(let q=1;q<=30;q++){await expect(page.locator('#qNumber')).toHaveText(q+' / 30');if(q%5===0){const buttons=page.locator('#qAnswer button');await expect(buttons).toHaveCount(4);const vals=await buttons.evaluateAll(bs=>bs.map(b=>b.dataset.value));expect(new Set(vals).size).toBe(4);await page.locator('#qAnswer button[data-value="Yes"]').click()}else{await page.locator('#qAnswer input').fill('42');await page.locator('#checkAnswer').click()}await expect(page.locator('#qFeedback')).toContainText('Correct');await page.locator('#nextQuestion').click()}await expect(page.locator('#resultCard')).toContainText('30 out of 30 correct')})
test('wrong answer gives strategy feedback without exposing raw answer field',async({page})=>{await open(page);await page.locator('[data-screen="challenge"]').click();await page.locator('#qAnswer input').fill('41');await page.locator('#checkAnswer').click();await expect(page.locator('#qFeedback')).toContainText('Not quite. Use factors, multiples and divisibility rules.')})
test('challenge fails closed without protected service',async({page})=>{await page.route('**/js/factors-multiples-auth.js*',r=>r.abort());await page.goto('/factors-multiples.html');await page.evaluate(()=>document.body.classList.remove('auth-loading'));await page.locator('[data-screen="challenge"]').click();await expect(page.locator('#qPrompt')).toHaveText('Challenge temporarily unavailable');await expect(page.locator('#qAnswer')).toBeEmpty()})
test('desktop and mobile layout stays within viewport',async({page})=>{for(const vp of [{width:1280,height:800},{width:390,height:844}]){await page.setViewportSize(vp);await open(page);await page.locator('[data-screen="challenge"]').click();const m=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,w:document.querySelector('.quiz-card').getBoundingClientRect().width}));expect(m.sw).toBeLessThanOrEqual(m.cw+1);expect(m.w).toBeLessThanOrEqual(vp.width)}})
test('external resources use original links and privacy-enhanced embed',async({page})=>{await open(page);const hrefs=await page.locator('a.resource-link').evaluateAll(as=>as.map(a=>a.href));expect(hrefs.some(h=>h.includes('khanacademy.org'))).toBeTruthy();expect(hrefs.some(h=>h.includes('youtube.com/watch?v=1qPfLkOEuYY'))).toBeTruthy();const frame=page.locator('iframe[src*="youtube-nocookie.com/embed/1qPfLkOEuYY"]');await expect(frame).toHaveAttribute('loading','lazy');await expect(frame).toHaveAttribute('title',/Mr\. J/);await expect(frame).toHaveAttribute('allowfullscreen','')})
test('dashboard exposes Factors and Multiples as an active topic',async({page})=>{await page.goto('/dashboard.html');const card=page.locator('a[href="factors-multiples.html"]');await expect(card).toHaveCount(1);await expect(card).toContainText('Factors & Multiples')})