const{test,expect}=require('@playwright/test');
const levels=['FOUNDATION','DEVELOPING','DEVELOPING +','PROFICIENT','APPLICATION','CHALLENGE'];
function questions(){const families=['Multiplication','Division','Unknown Value','Estimation','Remainders','Division result','Modelling','Two-step Reasoning','Reasoning','Error Analysis'];return Array.from({length:30},(_,i)=>({index:i+1,total:30,level:levels[Math.floor(i/5)],topic:i===12||i===22?'Division result':families[Math.min(Math.floor(i/3),families.length-1)],prompt:i===12?'Express the result as a decimal.':i===22?'Which mixed number represents the result?':'Solve this Year 5 multiplication or division question.',display:i===12?'23 ÷ 4':i===22?'23 ÷ 4':'24 × 6',type:i===22?'choice':'number',...(i===22?{options:['5 3⁄4','6 3⁄4','5','4 3⁄4']}:{})}))}
async function open(page){const qs=questions();await page.addInitScript(qs=>{let pos=0;window.__MM_QS=qs;window.MathMagicMultiplicationDivisionProtected={start:async()=>({sessionId:'ci-session',question:qs[0]}),submit:async(_s,i,response)=>{const correct=(i===12&&String(response)==='5.75')||(i===22&&response==='5 3⁄4')||(i!==12&&i!==22&&String(response)==='144');pos=i+1;return{correct,solution:'Use the taught strategy.',answer:null,score:0,complete:pos>=30,nextIndex:pos,question:pos<30?qs[pos]:null}}};window.MathMagicMultiplicationDivisionProgress={saveAttempt:async score=>({bestScore:score})}},qs);await page.route('**/js/multiplication-division-auth.js*',r=>r.abort());await page.goto('/multiplication-division.html');await page.evaluate(()=>document.body.classList.remove('auth-loading'))}
test('five lessons render',async({page})=>{await open(page);for(const id of ['lesson1','lesson2','lesson3','lesson4','lesson5','challenge']){await page.locator('[data-screen="'+id+'"]').click();await expect(page.locator('#'+id)).toHaveClass(/active/)}})
test('lesson fractions use stacked notation with no vulgar or slash fraction leak',async({page})=>{await open(page);await page.locator('[data-screen="lesson4"]').click();const lesson=page.locator('#lesson4');await expect(lesson).not.toContainText('¾');await expect(lesson).not.toContainText(/\b3\/4\b/);await expect(lesson.locator('.stacked-fraction')).toHaveCount(2)})
test('protected adapter completes all 30 positions including decimal and mixed-fraction division results',async({page})=>{await open(page);await page.locator('[data-screen="challenge"]').click();for(let q=1;q<=30;q++){await expect(page.locator('#qNumber')).toHaveText(q+' / 30');if(q===23){await expect(page.locator('#qAnswer')).not.toContainText('3/4');await expect(page.locator('#qAnswer .stacked-fraction')).toHaveCount(3);await page.locator('#qAnswer button[data-value="5 3⁄4"]').click()}else{await page.locator('#qAnswer input').fill(q===13?'5.75':'144');await page.locator('#checkAnswer').click()}await expect(page.locator('#qFeedback')).toContainText('Correct');await page.locator('#nextQuestion').click()}await expect(page.locator('#resultCard')).toContainText('30 out of 30 correct')})
test('challenge feedback uses consistent green correct and red incorrect states',async({page})=>{await open(page);await page.locator('[data-screen="challenge"]').click();await page.locator('#qAnswer input').fill('144');await page.locator('#checkAnswer').click();await expect(page.locator('#qFeedback')).toHaveClass(/correct/);expect(await page.locator('#qFeedback').evaluate(e=>getComputedStyle(e).color)).toBe('rgb(24, 121, 78)');await page.locator('#restartQuiz').click();await page.locator('#qAnswer input').fill('145');await page.locator('#checkAnswer').click();await expect(page.locator('#qFeedback')).toHaveClass(/incorrect/);expect(await page.locator('#qFeedback').evaluate(e=>getComputedStyle(e).color)).toBe('rgb(180, 35, 24)')})
test('challenge fails closed without protected service',async({page})=>{await page.route('**/js/multiplication-division-auth.js*',r=>r.abort());await page.goto('/multiplication-division.html');await page.evaluate(()=>document.body.classList.remove('auth-loading'));await page.locator('[data-screen="challenge"]').click();await expect(page.locator('#qPrompt')).toHaveText('Challenge temporarily unavailable');await expect(page.locator('#qAnswer')).toBeEmpty()})
test('desktop and mobile layout stays within viewport',async({page})=>{for(const vp of [{width:1280,height:800},{width:390,height:844}]){await page.setViewportSize(vp);await open(page);await page.locator('[data-screen="challenge"]').click();const m=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,w:document.querySelector('.quiz-card').getBoundingClientRect().width}));expect(m.sw).toBeLessThanOrEqual(m.cw+1);expect(m.w).toBeLessThanOrEqual(vp.width)}})
test('external resources and privacy-enhanced embed are present',async({page})=>{await open(page);const hrefs=await page.locator('a.resource-link').evaluateAll(as=>as.map(a=>a.href));expect(hrefs.some(h=>h.includes('khanacademy.org'))).toBeTruthy();expect(hrefs.some(h=>h.includes('youtube.com/watch?v=FJ5qLWP3Fqo'))).toBeTruthy();const frame=page.locator('iframe[src*="youtube-nocookie.com/embed/FJ5qLWP3Fqo"]');await expect(frame).toHaveAttribute('loading','lazy');await expect(frame).toHaveAttribute('title',/Math Antics/);await expect(frame).toHaveAttribute('allowfullscreen','')})
