const fs=require('fs'),assert=require('assert');
const auth=fs.readFileSync('js/factors-multiples-auth.js','utf8'),client=fs.readFileSync('js/factors-multiples.js','utf8'),html=fs.readFileSync('factors-multiples.html','utf8'),fractions=fs.readFileSync('js/fractions-auth.js','utf8');
assert(auth.includes('onAuthStateChanged'));
assert(auth.includes('doc(db,"access",user.uid)'));
assert(auth.includes('access.data().approved===true'));
assert(auth.includes('location.replace("index.html")'));
assert(auth.includes('location.replace("access-required.html")'));
assert(auth.includes('doc(db,"progress",uid,"topics",topicId)'));
assert(auth.includes('setDoc(ref(user.uid),data)'));
assert(auth.includes('localStorage.setItem'));
assert(auth.includes('MathMagicFactorsMultiplesProgress'));
assert(!auth.includes('getFunctions')&&!auth.includes('httpsCallable'));
assert(client.includes('function buildFactorsMultiples()'));
assert(client.includes('quiz=buildFactorsMultiples()'));
assert(client.includes('current.answer'));
assert(html.includes('js/factors-multiples-auth.js?v=2'));
assert(html.includes('js/factors-multiples.js?v=3'));
for(const token of ['onAuthStateChanged','access.data().approved===true','localStorage.setItem','setDoc'])assert(auth.includes(token)&&fractions.includes(token));
console.log('Factors & Multiples Fractions-style authenticated architecture passed');
